#!/usr/bin/env python

import glob
import os
import fnmatch

sourceFiles = []

for root, dirs, files in os.walk("src"):
    sourceFiles += [os.path.relpath(os.path.join(root, fn), "src") for fn in files if fnmatch.fnmatch(fn, '*.cpp')]

def build(bld):
    game = bld(source=sourceFiles,
               name="game",
               target="game",
               cxxflags=["-g", "-I../src"],
               framework="OpenGL GLUT CoreServices",
               features="cxx cxxprogram")