#!/usr/bin/env python

import glob
import os
import fnmatch

sourceFiles = []

for root, dirs, files in os.walk("src"):
    sourceFiles += [os.path.relpath(os.path.join(root, fn), "src") for fn in files if fnmatch.fnmatch(fn, '*.cpp')]

def build(bld):
    bld.program(source=sourceFiles,
                target="game",
                includes=[".", "../external/tinythread"],
                cxxflags=["-g"],
                framework="OpenGL CoreServices",
                uselib="glog",
                use="tinythread")